# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0b1b85b43c6718a0cdaf2c5a4b7c45e5e7b311b8ab0cdf2dd923f8c39a85c99f07ff1201e524282767f2f8d2230bb0263f0a5811e4ec5092c213009481c3148

test:
  secret_key_base: f4601f410d152eaf15054aedfc19f973088789df6e7dde4102d6afd9d9ca3da4c15295b37d00198fcabdc3c3514c2b653d7864b494221bf43f64280e594074e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
